---
# Two handlers to reload or run the nginx service
- name: "Start nginx"
  become: yes
  service: name=nginx state=started

- name: "Reload nginx"
  become: yes
  service: name=nginx state=reloaded
       
