---
#adding nginx repo
- name: "Add nginx repo"
  become: yes
  apt_repository: 
     repo: ppa:nginx/stable #repo name 
     update_cache: yes      # this equivalent to (apt-get update) when a change occurs.  Cache updates are run after making changes.
     state: present         # state of pkg
  register: ppastable

# installing ngnix
- name: "Install Nginx"
  become: yes
  apt:                      #installing apt package
      name: nginx           #package Name
  when: ppastable|success   #this will run when repo is added successfully 
  register: nginxinstalled
  notify:                   #trigger the start nginx handler
    - Start nginx
